steps:
  # ステップ1: ソースコードのクローン
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/ユーザー名ikemoto226/Calendar']

  # ステップ2: Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/calendar-app', '.']

  # ステップ3: ビルドしたイメージをGoogle Container Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/calendar-app']

  # ステップ4: 依存関係のインストールとテストの実行
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']

  # ステップ5: GKEにデプロイメントを適用
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'autopilot-cluster-1', '--zone', 'asia-east1', '--project', '$PROJECT_ID']

  # ステップ6: kubectlを使用してデプロイメントとサービスを適用
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'

images:
  - 'gcr.io/$PROJECT_ID/calendar-app'
